name: "pia_spots"
comments: "Pia spots full dataset, no augmentation, yes dropout, np.max norm"
dataset: "SpotsDataset"
dataset_args:
    version: "pia_spots_ae714f3b"
    cell_size: 4
    flip: False
    illuminate: False
    rotate: False
    gaussian_noise: False
    translate: False
model: "SpotsModel"
network: "resnet"
network_args:
    n_channels: 3
loss: "binary_crossentropy"
optimizer: "adam"
train_args:
    batch_size: 1
    epochs: 2000
    learning_rate: 3e-5
