name: "Ivana_spots"
comments: "Ivana spots full dataset: dropout + flip + np.max norm"
dataset: "SpotsDataset"
dataset_args:
    version: "ivana_spot_fb2749af"
    cell_size: 4
    flip: True
    illuminate: False
    rotate: False
    gaussian_noise: False
    translate: False
model: "SpotsModel"
network: "resnet"
network_args:
    n_channels: 3
loss: "binary_crossentropy"
optimizer: "adam"
train_args:
    batch_size: 1
    epochs: 1000
    learning_rate: 3e-5
