wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.33
    code_path: code/training/run_experiment.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
comments:
  desc: null
  value: Spot overfitting.
dataset:
  desc: null
  value: SpotsDataset
dataset_args:
  desc: null
  value:
    version: spots_synt4_af4f7386
loss:
  desc: null
  value: binary_crossentropy
model:
  desc: null
  value: SpotsModel
name:
  desc: null
  value: octo-guacamole-spots
network:
  desc: null
  value: fcn
network_args:
  desc: null
  value:
    n_channels: 1
optimizer:
  desc: null
  value: adam
system:
  desc: null
  value:
    gpus: []
    platform: Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
    version: '#1 SMP Tue Mar 17 23:49:17 UTC 2020'
train_args:
  desc: null
  value:
    batch_size: 1
    epochs: 1000
    learning_rate: 3e-4
